version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./app/nginx/config/conf.d:/etc/nginx/conf.d:rw
      - ./app/nginx/config/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./app/nginx/log:/var/log/nginx:rw
      - ./web:/etc/nginx/html:rw
    ports:
      - "${NGINX_LOCAL_PORT}:80"
    restart: always
    networks:
      - net-php

  php:
    build:
      context: ./source/php
      args:
        PHP_SSH_LINK_MODE: ${PHP_SSH_LINK_MODE}
        PHP_SSH_ID_PUB: ${PHP_SSH_ID_PUB}
        PHP_SSH_PASSWORD: ${PHP_SSH_PASSWORD}
    volumes:
      - ./web/:/etc/nginx/html:rw
      - ./app/php/log:/var/log:rw
      - ./app/php/config/php.ini:/usr/local/etc/php/php.ini:rw
      - ./app/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./app/php/start.sh:/home/start.sh:rw
    restart: always
    ports:
      - "${PHP_SSH_LOCAL_PORT}:22"
    expose:
      - "9000"
      - "9001" ### 用于nginx反向代理swoole服务
    networks:
      - net-php
      - net-mysql
      - net_redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - ./app/mysql/data:/var/lib/mysql:rw
      - ./app/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
      - ./app/mysql/log:/var/log/mysql:rw
    networks:
      - net-mysql

  redis:
    image: redis:4.0
    restart: always
    ports:
      - "${REDIS_LOCAL_PORT}:6379"
    volumes:
      - ./app/redis/log:/var/log/redis:rw
      - ./app/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:rw
    networks:
      - net_redis

  memcached:
    image: memcached:1.5.12-alpine
    restart: always
    expose:
      - "11211"
    networks:
      - net-php

  mongodb:
    image: mongo
    restart: always
    ports:
      - "${MONGODB_LOCAL_PORT}:27017"
    volumes:
      - ./app/mongodb/data:/data/db
      - ./app/mongodb/configdb:/data/configdb
    networks:
      - net-php

  elasticsearch:
    build:
      context: ./source/elasticsearch
    restart: always
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
    networks:
      - net-php

networks:
  net-php:
  net-mysql:
  net_redis: